name: payflow-dev

services:
  db:
    image: postgres:17
    container_name: my_postgres_payflow_dev
    environment:
      POSTGRES_USER: postgres_payflow
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: payflow_db_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local